### PR TITLE
64 pin swaped with 48

### PR DESCRIPTION
**Pull request by suzonch**
Please review this, everything is supposed to stay unchanged just the bable part 64>48 pin.

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
It has to be merged if we're going to manufacture it. No released docs --> no manufacturing.

I would like to withdraw the request for my review, let Dmitry approve it.

**Comment by suzonch** [comment]
Okay, I'll publish the release once reviewed.

**Comment by dimracer** [comment]
@suzonch it seems you haven't changed the pcb file. Please check.

**Comment by suzonch** [comment]
There's basically no change, it's just the 48 pin mcu is used instead of 64 that's why the IC placement box is showing 48 pin mcu

**Pull request merged**
